<%
'::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
'::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
'<> Copyright (C) 2005-2008 Dogg Software All Rights Reserved
'<>
'<> By using this program, you are agreeing to the terms of the
'<> SkyPortal End-User License Agreement.
'<>
'<> All copyright notices regarding SkyPortal must remain 
'<> intact in the scripts and in the outputted HTML.
'<> The "powered by" text/logo with a link back to 
'<> http://www.SkyPortal.net in the footer of the pages MUST
'<> remain visible when the pages are viewed on the internet or intranet.
'<>
'<> Support can be obtained from support forums at:
'<> http://www.SkyPortal.net
'::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
'::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

const strWebSiteMVersion = "1.0"
tempArr = split(strWebMaster, ",")
strSiteOwner = tempArr(0)

dim pmimage, pmCount

if not isObject(my_Conn) then
  on error resume next
	set my_Conn = Server.CreateObject("ADODB.Connection")
	my_Conn.Errors.Clear
	my_Conn.Open strConnString
	'	Lets check to see if the strConnString or db path has changed
		if my_conn.Errors.Count <> 0 then 
		  'we can't connect, lets log the error
		  for counter = 0 to my_conn.Errors.Count -1
			ConnErrorNumber = my_conn.Errors(counter).Number
			ConnErrorDesc = my_conn.Errors(counter).Description
			if ConnErrorNumber <> 0 and ConnErrorNumber <> -2147217887 then 
			  writeToLog "Database","",ConnErrorNumber & " : " & ConnErrorDesc
			end if
		  next
		  if ConnErrorNumber <> -2147217887 then
			my_conn.Errors.Clear 
			set my_Conn = nothing
			on error goto 0
			Response.Redirect "site_setup.asp?RC=1"
		  end if
		end if
  on error goto 0
end if
  
if not uploadPg then  
  chkLogInOut()
end if

':: check login status - member or guest
chkLoginStatus()

':: populate visitor member groups array
bldArrUserGroup()

':: Check for Site Lockdown
chkSiteLockDown()

  'get current user skin
  getPageSkin(arrGroups(0,0))
  %>
<!-- #include file="files/config/core_icons.asp" -->
<!-- #include file="files/config/custom_icons.asp" -->
  <%  

'this populates the arrCurOnline() array with online users membername and IP
if bOnlineUsers then
  buildOnlineUsersArray() 
end if
	  
if trim(curpagetype) <> "" and curpagetype <> "home" and curpagetype <> "register" and curpagetype <> "core" then
    if not chkApp(curpagetype,"USERS") then
	  closeAndGo("error.asp?type=noperm")
	end if
end if

if strDBNTUsername <> "" then
  if chkApp("PM","USERS") and PMaccess > 0 then '
  	'checks and sets the members PM count
  	pmCheck()
  end if
end if

Dim strOnlineGuestsCount, strOnlineMembersCount

Dim strOnlineUser, strOnlineUserAgent, strOnlineUserIP

if strDBNTUserName = "" then
	strOnlineUser = txtGuest
else
	strOnlineUser = strDBNTUserName
end if
'
' Set Super admins IP to 0.0.0.0
if intIsSuperAdmin then
  arrWeb = split(left(strWebMaster,len(strWebmaster)-1),",")
  for olu = 0 to ubound(arrWeb)
    if lcase(strOnlineUser) = lcase(arrWeb(olu)) then
	  strOnlineUserIP = "0.0.0." & (olu + 1)
	end if
  next
  set arrWeb = nothing
else
  strOnlineUserIP = Request.ServerVariables("REMOTE_ADDR")
end if

tmpOnlineUserAgent = Request.ServerVariables("HTTP_USER_AGENT")
tmpAgent = split(tmpOnlineUserAgent," ")
strOnlineUserAgent = tmpAgent(0)
':::::: end onlone users table code :::::::::::::::::::::::::::

' Gets the current page title
CurPageTitle = UCase(Mid(CurPageType, 1, 1)) & Mid(CurPageType, 2, Len(CurPageType))

Response.Write("<!DOCTYPE html PUBLIC ""-//W3C//DTD XHTML 1.0 Transitional//" & ucase(strLang) & """ ""http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"">")
Response.Write("<html>")
Response.Write("<head>")
Response.Write("<!-- This page is generated by SkyPortal / SkyPortal.net " & strCurTimeAdjust & " -->")
Response.Write("<link rel=""shortcut icon"" href=""" & strHomeURL & "favicon.ico"" type=""image/x-icon"" />")

getMetaTags()

tmpPageTitle = ""
tmpPageTitle = strSiteTitle
if not CurPageType = "" and not uploadPg = true then
'tmpPageTitle = strSiteTitle & " | " & CurPageTitle
select case CurPageType
 case "forums"
	if not ChkString(Request("FORUM_Title"),"display") = " " then
	CurForumTitle =  " | " & ChkString(Request("FORUM_Title"),"display")
	else
	CurForumTitle = ""
	end if
	if not ChkString(Request("TOPIC_Title"),"display") = " " then
	CurTopicTitle = ChkString(Request("TOPIC_Title"),"display") & " - "
	else
	CurTopicTitle = ""
	end if
	tmpPageTitle = CurTopicTitle & strSiteTitle & " | " & CurPageTitle & CurForumTitle
 case "core"
    tmpPageTitle = PageTitle & " | " & strSiteTitle
 case else
    if PageTitle <> "" then
	  tmpPageTitle = PageTitle & " | " & strSiteTitle
	else
	  tmpPageTitle = CurPageTitle & " | " & strSiteTitle
	end if
 end select 
end if

Response.Write("<title>" & tmpPageTitle & "</title>")

 '######## RSS MODULE CODE ######
If chkApp("skynews","USERS") Then
  addRSSXML strSiteTitle & " News",strHomeURL & "files/rss/xml/SiteNews.xml"
end if

spThemeHeader_style()
getCSSfile()

getRSSXML()

%>
<script type="text/javascript" >
// populate variables for use in the JS include files
 var js_welcome = "<%= txtWelcomeTo & " " & strSiteTitle %>";
 var txttype="<%= varBrowser %>";
 var js_collapse = "<%= txtCollapse %>";
 var js_expand = "<%= txtExpand %>";
 var js_none = "<%= txtNone %>";
 var js_member = "<%= txtMember %>";
 var js_admin = "<%= txtAdmin %>";
 
//  month/day arrays
 var js_months_lng=new Array("<%= txtJanuary %>", "<%= txtFebruary %>", "<%= txtMarch %>", "<%= txtApril %>", "<%= txtMay %>", "<%= txtJune %>", "<%= txtJuly %>", "<%= txtAugust %>", "<%= txtSeptember %>", "<%= txtOctober %>", "<%= txtNovember %>", "<%= txtDecember %>");
 var js_days_lng=new Array("<%= txtSunday %>", "<%= txtMonday %>", "<%= txtTuesday %>", "<%= txtWednesday %>", "<%= txtThursday %>", "<%= txtFriday %>", "<%= txtSaturday %>", "<%= txtSunday %>");
 
// pop-up calendar items
 var js_calendar = "<%= txtCalendar %>";
 var js_frm = "<%= txtForm %>";
 var js_frmfld = "<%= txtFrmFld %>";
 var js_notfnd = "<%= txtNotFound %>";
 var yxLinks=new Array("[<%= txtClose %>]", "[<%= txtClear %>]");
 
 var jsUniqueID = "<%= strUniqueID %>";

 var calFormat="<%= strDateFormat %>";
 // preload min-max images
  var mmImages = new Array(4);
  mmImages[0] = "Themes/<%= strTheme %>/icon_max.gif";
  mmImages[1] = "Themes/<%= strTheme %>/icon_min.gif";
  mmImages[2] = "Themes/<%= strTheme %>/icon_max1.gif";
  mmImages[3] = "Themes/<%= strTheme %>/icon_min1.gif";
  
  function jumpToPage(s) {if (s.selectedIndex != <%=mypage-1%>) top.location.href = s.options[s.selectedIndex].value;return 1;}
</script>
<%

addJSfile("includes/scripts/prototype.js")
addJSfile("includes/scripts/core.js")
addJSfile("includes/scripts/menu_com.js")
addJSfile("includes/scripts/effects.js")
addJSfile("includes/scripts/window.js")
addJSfile("includes/scripts/sp_ajax.js")
addJSfile("includes/scripts/cal2.js")
addJSfile("modules/custom_scripts.js")
if hasEditor = true and editorType = "tinymce" and strAllowHtml = 1 then
  addJSfile("tiny_mce/tiny_mce.js")
End If

getJSFiles()
%>
<!--#include file="includes/inc_editor.asp"-->
<!--#include file="includes/inc_header.asp"-->
<% navBarTop() %>
<!--#include file="includes/inc_nav_bar.asp"-->
<% navBarBottom()

if strForumStatus = "down" and CurPageType = "forums" and NOT intIsSuperAdmin then
  closeAndGo("error.asp?type=forumdown")
end if
%>
<!--#include file="includes/inc_ipgate.asp" -->