<%
'::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
'::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
'<> Copyright (C) 2005-2008 Dogg Software All Rights Reserved
'<>
'<> By using this program, you are agreeing to the terms of the
'<> SkyPortal End-User License Agreement.
'<>
'<> All copyright notices regarding SkyPortal must remain 
'<> intact in the scripts and in the outputted HTML.
'<> The "powered by" text/logo with a link back to 
'<> http://www.SkyPortal.net in the footer of the pages MUST
'<> remain visible when the pages are viewed on the internet or intranet.
'<>
'<> Support can be obtained from support forums at:
'<> http://www.SkyPortal.net
'::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
'::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

'<>:<>:<>:<>:<>:<>:<>:<>:<>:<>:<>:<>:<>:<>:<>:<>:<>:<>:<>:<>:
'<>:<>:<>:<>:<>:<>:<>:<>:<>:<>:<>:<>:<>:<>:<>:<>:<>:<>:<>:<>:
'<>:<>:
'<>:<>:  	DO NOT EDIT THIS FILE!
'<>:<>:
'<>:<>:		If you need to edit any items in this file, copy 
'<>:<>:		it from here to the custom_icons.asp file and 
'<>:<>:		edit it there. That file will override this file
'<>:<>:
'<>:<>:<>:<>:<>:<>:<>:<>:<>:<>:<>:<>:<>:<>:<>:<>:<>:<>:<>:<>:
'<>:<>:<>:<>:<>:<>:<>:<>:<>:<>:<>:<>:<>:<>:<>:<>:<>:<>:<>:<>:

icnSpacer = "images/spacer.gif"
icnLine = "themes/" & strTheme & "/icons/line.gif"
icnGoUp = "themes/" & strTheme & "/icons/go_up.gif"
icnNew1 = "themes/" & strTheme & "/icons/new1.gif"  'New since last visit
icnNew2 = "themes/" & strTheme & "/icons/new2.gif"  'New in last 7 days
icnNew3 = "themes/" & strTheme & "/icons/new3.gif"  'New in last 14 days
icnUpdate1 = "themes/" & strTheme & "/icons/update1.gif"
icnUpdate2 = "themes/" & strTheme & "/icons/update2.gif"
icnUpdate3 = "themes/" & strTheme & "/icons/update3.gif"
icnArLeft = "themes/" & strTheme & "/icons/arrow_left.gif"
icnArRight = "themes/" & strTheme & "/icons/arrow_right.gif"
icnDArLeft = "themes/" & strTheme & "/icons/widearrowleft.gif"
icnDArRight = "themes/" & strTheme & "/icons/widearrowright.gif"
icnPlus = "themes/" & strTheme & "/icons/plus.gif"
icnCheck = "themes/" & strTheme & "/icons/check.gif"
icnCopy = "themes/" & strTheme & "/icons/copy.gif"
icnEdit = "themes/" & strTheme & "/icons/edit.gif"
icnDelete = "themes/" & strTheme & "/icons/delete.gif"
icnLock = "themes/" & strTheme & "/icons/lock.gif"
icnUnLock = "themes/" & strTheme & "/icons/unlock.gif"
icnColor = "themes/" & strTheme & "/icons/color.gif"
icnBinoc = "themes/" & strTheme & "/icons/binocs.gif"
icnPrint = "themes/" & strTheme & "/icons/printer.gif"
icnEmail = "themes/" & strTheme & "/icons/email.gif"
icnToolbox = "themes/" & strTheme & "/icons/toolbox.gif"
icnHelp = "themes/" & strTheme & "/icons/help.gif"
icnInfo = "themes/" & strTheme & "/icons/info.gif"
icnAt = "themes/" & strTheme & "/icons/at.gif"
icnBar = "themes/" & strTheme & "/icons/bar.gif"
icnNewFolder = "themes/" & strTheme & "/icons/folder_new.gif"

icnFeature = "Themes/" & strTheme & "/icons/featured.gif"
icnUnfeature = "Themes/" & strTheme & "/icons/unfeature.gif"
icnSubscribe = "themes/" & strTheme & "/icons/subscribe.gif"
icnUnSubscribe = "themes/" & strTheme & "/icons/unsubscribe.gif"
icnBookmark = "themes/" & strTheme & "/icons/bookmark.gif"
icnUnBookmark = "themes/" & strTheme & "/icons/unbookmark.gif"
icnAccess = "themes/" & strTheme & "/icons/icon_access.gif"
icnAccessOn = "themes/" & strTheme & "/icons/icon_access_on.gif"
icnAccessOff = "themes/" & strTheme & "/icons/icon_access_off.gif"
icnOnline = "themes/" & strTheme & "/icons/online.gif"
icnOffline = "themes/" & strTheme & "/icons/offline.gif"
icnNav = "themes/" & strTheme & "/icons/nav_icon.gif"
icnSkyBlkOn = "themes/" & strTheme & "/icons/skyblock_on.gif"
icnSkyBlkOff = "themes/" & strTheme & "/icons/skyblock_off.gif"
icnRssOn = "themes/" & strTheme & "/icons/rss_sm_on.gif"
icnRssOff = "themes/" & strTheme & "/icons/rss_sm_off.gif"

':: the icons below also have larger counterparts.
':: Notice the prefix difference in the variables
icnDL = "themes/" & strTheme & "/icons/download.gif"
icnArticle = "themes/" & strTheme & "/icons/article.gif"
icnComment = "themes/" & strTheme & "/icons/comment.gif"
icnAttention = "themes/" & strTheme & "/icons/attention.gif"

imgDL = "themes/" & strTheme & "/icons/download_lg.gif"
imgComment = "themes/" & strTheme & "/icons/comment_lg.gif"
imgAttention = "themes/" & strTheme & "/icons/attention_lg.gif"
%>
